spring:
  thymeleaf:
    cache: false
    #thymeleaf 所在路径
    prefix: classpath:/templates/
    #thymeleaf 后缀
#    suffix: .html
    #thymeleaf 采用的标准
    mode: HTML
    #thymeleaf 编码格式
    encoding: UTF-8
  profiles:
    active: dev
#开启热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

comment.avatar: /images/avatar.png



