spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.129.118.199:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: root
    password: HY1998@
  #根据实体类属性更新数据库的表
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true #输出sql语句

logging:
  level:
    root: warn
    com.hy.blog: info
  file:
    path: log
    name: myblog-dev.log


#mybatis:
#  type-aliases-package: com.star.entity
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
server:
  port: 8081






